sudo: false

language: python

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test

notifications:
  email: false
  
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p _miniconda;  else  wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh && bash Miniconda3-latest-MacOSX-x86_64.sh -b -p _miniconda; fi
- export PATH="$PWD/_miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda install pytorch torchvision cpuonly -c pytorch
- conda install scipy=1.3.2

- git clone https://github.com/jurajHasik/tn-torch.git tn-torch && cd tn-torch
script: 
- python -m unittest discover -s examples -p "ctmrg_*.py"
- python -m unittest discover -s examples -p "optim_*.py"
