# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, models, travis ]
  pull_request:
    branches: [ master, models, travis ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_v: [3.6, 3.7, 3.8, 3.9]
        pytorch_v: [1.8.2, 1.9.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_v }}
      - name: setup pytorch
        run: |
          if [[ "${{ matrix.python_v }}" == "3.9" ]]; then export P39C="-c=conda-forge"; fi
          if [[ "${{ matrix.pytorch_v }}" == "1.8.2" ]]
          then
            $CONDA/bin/conda install pytorch cpuonly -c pytorch-lts ${P39C}
          else
            $CONDA/bin/conda install pytorch==${{ matrix.pytorch_v }} cpuonly -c pytorch ${P39C}
          fi
          $CONDA/bin/conda install scipy
          
      # Run tests
      - name: tests
        run: |
          $CONDA/bin/python -c "import sys; print(sys.path)"
          $CONDA/bin/python -m unittest discover -s examples -p "ctmrg_*.py"
          $CONDA/bin/python -m unittest discover -s examples -p "optim_*.py"
